[package]
name = "aoc2020_d3a"
version = "0.1.0"
authors = ["Joe Gilray <jgilray@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
